### ISSUE TITLE
Removing armor from jetpack

### ISSUE THREAD

**Issue by Drock1994** [CyberdyneCC/SimplyJetpacks-2#10]
When i take the armor off any jet pack i lose it. I have tried it with several different one and its gone.
simply jetpack 2 v1.10.2-2.0.2.14
forge v12.18.2.2107

**Comment by Tomson124** [comment]
You have probably EnderIO installed, too, it won't have to do anything with (at least I guess so) but please just tell me wich version of EnderIO you are using.

**Comment by Tomson124** [comment]
Please try it with the latest dev build: http://adf.ly/1eeGmt
Should be fixed there ;)

**Comment by Drock1994** [comment]
yes sorry 
Ender IO 3.0.1.123 beta
Ender Core 0.4.1.56 beta

and i will try the new dev build
Thanks

**Comment by Drock1994** [comment]
any idea when the lastest dev build will be on curse...i used a dev build in my pack and curse rejected it because that version was not on curse yet....i had to roll it back to the last version you have on curse

**Comment by Tomson124** [comment]
I will upload it as an alpha build if you want... But no idea how stable it is

**Comment by Tomson124** [comment]
Should be already fixed, just reopen it when it still is an issue
