### ISSUE TITLE
LivingTickHandler running for mobs?

### ISSUE THREAD

**Issue by Sir-Will** [CyberdyneCC/SimplyJetpacks-2#100]
is it intended that the LivingTickHandler is running for mobs?
![](https://i.imgur.com/xUEG0NL.jpg)

**Comment by thundr** [comment]
I believe this is intentional, as non-players can use jetpacks.

**Comment by Tomson124** [comment]
This originally was intentional but the code for using jetpcks on non-players was never finished. And it is quite useless now as the potato pack was removedd which you could use on mobs to see them fly and explode...

**Comment by thundr** [comment]
Yeah that's what I thought. In any case, this isn't an issue, but should be cleaned up.
