### ISSUE TITLE
Only creative jetpack ?

### ISSUE THREAD

**Issue by Trolox01** [CyberdyneCC/SimplyJetpacks-2#101]
Hi Dev, i have a modpack on Minecraft version 1.12.2 and i have a mod **Ender IO** and **Ender Core** but i don't have any jetpacks only creative jetpack i give you my list of mods : 

Aether 2
Backpacks 
BattleTowers 
BiomesOPleny 
Buildcraft 
CodeChickenLib 
ColossalChests 
Cucumber 
Custom mob spawner
Cyclops core 
Dungeons 2 
flux networks 
forge 
Gottsch core 
Gure 
Hwyla
jei 
Litleloader 
Chance Cube
Mantle 
mcjtylib 
Mo'creatures 
mysticalagriculture 
natura 
NotEnoughItems 
Optifine 
orbis api 
RedstoneFlux 
refined storage 
rftools 
rftoolsdim 
RoguelikeDingeons 
simplegenerators 
SimplyJetpacks 2 
sonarcore 
The Beneath 
tinyprogressions 
Damage Indicators 
TreCapitator 
twilight Forest 
valkyrielib 
VoxelMap 
Ender IO
Endercore 
Elevetor mod 
Gravestone mod

**Comment by thundr** [comment]
Is EnderIO integration enabled in the config?

**Comment by Giodan1026** [comment]
I'm Having the same issue as Trolox01
I tried to figure out the configs but im not that code savvy.

My mods list is:

CodeChichkenLib
CoFHCore
CoFHWorld
EnderCore
EnderIO
Gravestone
Iron Chest
JEI
JourneyMap
Mantle
OptiFine
RedstoneFlux
SimplyJetpacks2
TConstruct
ThermalDynamics
ThermalExpansion
ThermalFoundation
TinkerToolLeveling

**Comment by Trolox01** [comment]
Thanks to thundR becouse i have EnderIO integration disabled in the config,,,

**Comment by Giodan1026** [comment]
Where do i go in the config to enable it?

**Comment by thundr** [comment]
It's literally the first line in the config file simplyjetpacks.cfg

`    B:"Ender IO integration"=true`

You can find your configs in /config/ inside your minecraft directory

**Comment by thundr** [comment]
This does mean that EnderIO integration isn't being activated by default, I will look into that
