### ISSUE TITLE
Infused Jetplate refuses Thermal Foundation enchantments

### ISSUE THREAD

**Issue by SingABrightSong** [CyberdyneCC/SimplyJetpacks-2#102]
A number of armor enchantments added by Thermal Foundation, namely, Holding and Soulbound, cannot be legitimately added to the Jetplate. When applied  using Creative mode, the Holding enchantment has no effect, not multiplying the Jetplate's RF capacity as it does with the Infused Chestplate. As well, the Jetplate cannot be enchanted via enchanting table and must be combined with enchanted books using the anvil.

**Comment by thundr** [comment]
I think this is as easy as implementing IEnchantableItem but I will look into it more.

**Comment by thundr** [comment]
So I forgot we don't depend on CoFH mods anymore, so this isn't currently possible until KL opens up some stuff on the API side I guess. 
![image](https://user-images.githubusercontent.com/5940598/42004856-9c6be050-7a26-11e8-9dbe-3ada4e411481.png)

I'll reopen this if we get activity upstream. In the mean time, you're out of luck.

**Comment by thundr** [comment]
Spoke too soon
