### ISSUE TITLE
Texture Bug 

### ISSUE THREAD

**Issue by KyloRekt100** [CyberdyneCC/SimplyJetpacks-2#107]
I have installed Ender IO, Thermal Expansion and SimplyJetpacks2. Wearing Ender IO jetpack texture is normal, but Thermal Expansion Jetpacks have missing texture. 

![texture bug](https://user-images.githubusercontent.com/40855655/42317256-1c31c70c-804c-11e8-846a-8c5a93ff0693.png)

**Comment by thundr** [comment]
Version, log, anything?

**Comment by KyloRekt100** [comment]
Version: 1.10.2
Mod version: Newest

czw., 5 lip 2018, 21:17 użytkownik thundR <notifications@github.com>
napisał:

**Comment by thundr** [comment]
1.10 is not supported
