### ISSUE TITLE
[Suggestion] Add a config option to make the jetpack toggle message a status message

### ISSUE THREAD

**Issue by TheRandomLabs** [CyberdyneCC/SimplyJetpacks-2#108]
[Here](https://github.com/Tomson124/SimplyJetpacks-2/blob/c23a99992199c63bd2b8b2386311d548289e4d1f/src/main/java/tonius/simplyjetpacks/item/ItemJetpack.java#148), you could check if the option is enabled, and if so, call sendStatusMessage rather than sendMessage.

**Comment by Tomson124** [comment]
Better not making an option but make it standard, as this is the way minecraft/forge is recommending.

**Comment by TheRandomLabs** [comment]
Good idea. An option to disable the message entirely would be nice as well.
