### ISSUE TITLE
[BUG] Game doesn't respect custom controls.

### ISSUE THREAD

**Issue by UV-Husky** [CyberdyneCC/SimplyJetpacks-2#111]
When custom controls are setup the jetpack still uses the sneak key.
Simply Jetpacks 2: 1.12.2-2.2.7.45
Forge: 14.23.4.2738

**Comment by thundr** [comment]
Could you be more specific? Are you saying when there's a custom control set for the sneak key, that the mod doesn't respect that?

**Comment by UV-Husky** [comment]
I mean that in the mod config there is a value for custom fly and descend keys, instead of sneak and jump. Even if I set descend to 'alt' it still goes down using shift (sneak key)

**Comment by thundr** [comment]
Are you making sure the value is getting set? Your other issue has to do with config values not being set through the config gui ingame...

**Comment by thundr** [comment]
Also, are you talking about SJ2's config?

**Comment by UV-Husky** [comment]
Yes, I set them manually in the file after I discovered the other bug.

**Comment by UV-Husky** [comment]
Yes, SJ2

**Comment by Keridos** [comment]
Can conrifm this bug. Even with SimplyJetpacks2-1.12.2-2.2.9.58

/edit: descend key missing here? https://github.com/Tomson124/SimplyJetpacks-2/blob/1.12/src/main/java/tonius/simplyjetpacks/client/handler/KeyTracker.java#L64

**Comment by Keridos** [comment]
I found that the keys are not properly imported from the config. It always uses the default keys for custom controls.
