### ISSUE TITLE
[Request] Client side option to disable rendering of the capacitor bank

### ISSUE THREAD

**Issue by Hund** [CyberdyneCC/SimplyJetpacks-2#113]
It looks a bit weird when you use it with an elytra at the same time. :) It would be nice to either be able to disable the rendering of it via the config or perhaps adding an item like the phantom ink from Botania that makes their armor invincible when crafted with the armor and a bottle of the phantom ink.

![2018-07-24_19 54 19](https://user-images.githubusercontent.com/320498/43156808-6bf2983c-8f7b-11e8-8bb6-6d465d104fa7.png)

**Comment by Tomson124** [comment]
There is already an option in the configs to turn of the 3d armorm model. It is then just a plain icon on the back which isn't thicker than a chestplate.

**Comment by Hund** [comment]
Oh, thank you! :)
