### ISSUE TITLE
Game crashes when loading vanilla jetpacks

### ISSUE THREAD

**Issue by ConnorMiner** [CyberdyneCC/SimplyJetpacks-2#114]
When trying to start the game (client or server} with vanilla integration on, the game crashes whilst loading due to an error assigning the recipes.

Crash Log: https://drive.google.com/file/d/16hlV0myMDoVX0AXU7y88NHPVapDmBrd5/view?usp=sharing

**Comment by Tomson124** [comment]
They are not working at the moment and will be rewritten in the future.
