### ISSUE TITLE
[BUG] Can't seem to craft base thrusters on a 1.12.2 Forge server 

### ISSUE THREAD

**Issue by L4-2** [CyberdyneCC/SimplyJetpacks-2#115]
So there's a problem when trying to craft the conductive iron jetpack thrusters on a 1.12.2 Forge server. We tried between SJ2-1.12.2-2.2.7.45 and SJ-1.12.2-2.2.6.43 and still weren't able to craft in either version; we also tried switching to more recent versions of Forge and CoFH Core and still haven't been able to craft it on the server. Crafting and actual use of jetpacks work in singleplayer but whenever going on our server, it just doesn't decide to craft. Weird thing is, if you try to craft it in an auto workbench (Buildcraft), it starts to craft and stops 1/3 of the way. Just posting this here to see if it'll get fixed :D

**Comment by Tomson124** [comment]
Could you try this on a server with only SJ2, RF API and EnderIO? Maybe it is some recipe conflict where recipes were changed on the server.

A complete list of the mods would also be helpful.

**Comment by L4-2** [comment]
@Tomson124 Sorry about the delay, but basically, I've tried running the server with only those mods and the problem still persists. I tried switching mod versions again and still no fix. One interesting thing I found out though was that all the SJ2 items in ore dictionary were named,"metaimmods". I looked it up and it seems to be related to JEI or Forge's Ore Dictionary. I really am thinking it's some weird recipe conflict, but at this point I can't really pinpoint the problem :/.

I have a screenshot of the mods I have running on the server: https://drive.google.com/file/d/1DFaPBU4dxUysc7QGn8elh6Gri5a4ujhy/view?usp=sharing

**Comment by Tomson124** [comment]
Which wooden gears did you try to use for the recipe? Where they from EnderIO or Buildcraft?

**Comment by L4-2** [comment]
@Tomson124 I used the Ender IO gears as that's what JEI indicates the recipe is, though I have also tried the Buildcraft gears. Also, I accidentally spelled the JEI name incorrectly; it's supposed to be "metaitemmods" or meta item mods which yeild search results, which is kinda sad to have said it in quick succession and said it "met-TAITEM-mod"  D:

**Comment by Tomson124** [comment]
Did you try it without buildcraft, too? As everything is working just fine in my dev environment.

**Comment by Tomson124** [comment]
Any news on this?

**Comment by L4-2** [comment]
@Tomson124 Okay, I feel bad for leaving this issue open for some time again, but, had an interest in a modded survival server again, and tried to craft it again with no luck, but there was no actual bug or issue as before now, I never really looked at a mod's config file. Checking the config file for both client side and server side said that all integrations (including vanilla) were set to false. After changing this to true, FINALLY let me craft the thrusters. Sorry for the confusion, (lack of knowledge on my part), and keep up the great work. :D

**Comment by L4-2** [comment]
Although, I have noticed that this happens a lot, as I checked the older server's Simply Jetpack config, a personal survival world config file, and the new server's config file, and all had settings set to false. Kinda weird, but it's an easy fix ¯\_(ツ)_/¯.
