### ISSUE TITLE
[2.0.3.16] Crash when not using jetpack?

### ISSUE THREAD

**Issue by SPMoo66** [CyberdyneCC/SimplyJetpacks-2#12]
Using dev branch here, hope you don't mind...

I was just standing around looking at some machines, when my client crashed. I don't think I was even using the jetpack at the time, so I'm not really sure what happened here...

http://pastebin.com/5kZNiu7X

Edit: Actually, it looks like I might've been opening the GUI of an EnderIO capacitor bank at the time, which includes the armor slots, including the jetpack. It doesn't crash in that GUI normally, so I don't know what went wrong at the time. :/

Edit2: Another player on our server just had the exact same crash upon logging onto our server and walking forward a few steps, doing nothing else.

**Comment by Tomson124** [comment]
Did you try going back to the beta version (the latest on CurseForge) or used that version before? Did you have that problem with it, too?

**Comment by SPMoo66** [comment]
Sorry about the lack of reply, I don't seem to have noticed the email notification. No, we hadn't experienced that bug on a CurseForge version before, so I guess this is just the danger of using an unstable version.
It hasn't happened since those two times, so it seems very rare for it to happen at least.
I just thought you might be able to pull some useful information from the crashlog. I'll let you know if we have any trouble again.
