### ISSUE TITLE
Crash with version SimplyJetpacks2-1.12.2-2.2.8.56.jar

### ISSUE THREAD

**Issue by calloatti** [CyberdyneCC/SimplyJetpacks-2#121]
https://paste.dimdev.org/babipexudi.mccrash

**Comment by Tomson124** [comment]
First of all this is not really a proper issue report...
But for the issue itself. Could you try installing CoFHCore and see if it fixes this issue?

**Comment by calloatti** [comment]
What more information do you need that is not in the crash report?

**Comment by Tomson124** [comment]
Maybe if you tried something else than just starting the game? Changed some configs before the crash?
Btw, did you try what I suggested?

**Comment by PhoenyxStar** [comment]
I was having the same problem (running with RedstoneFlux and EnderIO), but CoFHCore fixes the problem. Kind of weird, but I'll take it.

No config changes had any effect.

**Comment by Tomson124** [comment]
This is due something depending on a interface in CoFHCore, will make it optional with the next update
