### ISSUE TITLE
New HUD incompatible with InGameInfoXML 2.8.2.94

### ISSUE THREAD

**Issue by marckskl** [CyberdyneCC/SimplyJetpacks-2#122]
The new HUD implementation in SJ2 2.2.8.56 isn't compatible with InGameInfoXML v2.8.2.94. I removed InGameInfoXML and the JetPack HUD comes up fine in the default top left corner. I re-enable InGameInfoXML and the jetpack HUD disappears. 

InGameInfoXML: 2.8.2.94
Simply Jetpacks 2: 2.2.8.56
Forge: 14.23.4.2760

**Comment by Tomson124** [comment]
Well that is weird, the new HUD was made with the intention of better compatability...
I will have a look into it.
