### ISSUE TITLE
food bar and armor bar glish out

### ISSUE THREAD

**Issue by jotac0** [CyberdyneCC/SimplyJetpacks-2#123]
after i installed SimplyJetpacks2-1.12.2-2.2.9.58 i saw that my hud of the food and armor was glished, when i open the inventory it goes back to normal.

**Comment by Tomson124** [comment]
Could you please provide a screenshot? A list of the installed mods?

**Comment by jotac0** [comment]
in single player, normal game hud:
https://imgur.com/a/y2TCi5n

with inventory screen opened
https://imgur.com/a/RLmeAo2

when i take off the jetpack
https://imgur.com/a/dUHSuIH


list of mods:
EnderCore-1.12.2-0.5.41
EnderIO-1.12.2-5.0.35
jei_1.12.2-4.11.0.202
journeymap-1.12.2-5.5.2
moreoverlays-1.14-mc1.12.2
RebornCore-1.12.2-3.10.1.335-universal
RedstoneFlux-1.12-2.0.2.3-universal
SimplyJetpacks2-1.12.2-2.2.9.58
stackable-1.12.2-1.3.2
StevesCarts-1.12.2-2.4.24.118
twilightforest-1.12.2-3.8.689-universal


i had to revert to SimplyJetpacks2-1.12.2-2.2.7.45 so the issue disapiars.

**Comment by Tomson124** [comment]
Issue persists with 2.2.8, too?

**Comment by jotac0** [comment]
with 2.2.8 i get this error: 
https://pastebin.com/qUgE42Te

**Comment by Tomson124** [comment]
The error occurs because CoFHCore is not installed, was a hard dependency in that version.

**Comment by jotac0** [comment]
with CoFH Core and Redstone FLux installed i get no glish
using version SimplyJetpacks2-1.12.2-2.2.8.56

**Comment by Zhythero** [comment]
Hi, currently having same issue with `SimplyJetpacks2-1.12.2-2.2.9.58`

I have `CoFHCore-1.12.2-4.6.1.22-universal` and `RedstoneFlux-1.12-2.1.0.6-universal` installed.

**Comment by Tomson124** [comment]
@Zhastreaus Could you also try to use version 2.2.8 of SJ2? So I maybe can narrow it down to the latest update.

**Comment by bochen415** [comment]
2.2.8.56 is working as expected
2.2.9.60 doesn't
![](https://i.imgur.com/KNoQumx.png)
@Jaari asked me to change `0xeeeeee` to `0xafffff` in
https://github.com/Tomson124/SimplyJetpacks-2/blob/1.12/src/main/java/tonius/simplyjetpacks/client/handler/HUDTickHandler.java#L40
just for the heck of it so I did
![](https://i.imgur.com/lnDsmTu.png)

**Comment by Tomson124** [comment]
@bochen415 What mods do you have installed? HAve you tried running it with just SJ2, Thermal mods and /or EnderIO?

**Comment by bochen415** [comment]
My pack is kinda heavy but I can minimize the set of mods to help you recreate the problem.
_20 minutes of testing later_

Mods:
![](https://i.imgur.com/hHgNjLv.png)

MinecraftForge: 1.12.2-14.23.5.2768
Launcher: MultiMC

Screenshot of the problem:
![](https://i.imgur.com/243BRx3.png)

When using the inventory the problem is gone:
![](https://i.imgur.com/LEiFkBo.png)

Other things to note: the graphical glitch looks different after removing the EnderIO mods group.
With EnderIO it was like in my previous message.

Edit: only happens when you have a jetpack on you.

**Comment by Tomson124** [comment]
@Zhastreaus @bochen415 @jotac0 Could you please try the latest build from the [jenkins server](http://modmuss50.me:8080/job/SimplyJetpacks-2/job/SimplyJetpacks-2-1.12/) and see if it fixes the problem?

**Comment by bochen415** [comment]
After a brief test looks like the glitch is gone :+1:

**Comment by jotac0** [comment]
can confirm, issue gone in SimplyJetpacks2-1.12.2-2.2.9.61  :D 
using ender IO
