### ISSUE TITLE
Soularium Ingot

### ISSUE THREAD

**Issue by FallenEagle1** [CyberdyneCC/SimplyJetpacks-2#127]
Was asked about this in a modpack, is there plans for adding a recipe for the dark soularium ingot? It looks like the dark soularium jetplate is all functional and has all the recipes needed to make it, all but that ingot.

Was thinking of potential recipes to use to make this, but want to check to see what was planned.

**Comment by loper12** [comment]
Should be fixed now.

**Comment by Dolphin2Point1** [comment]
Fixed in the new DEV.
