### ISSUE TITLE
Emergency hover doesn't work

### ISSUE THREAD

**Issue by Jomik** [CyberdyneCC/SimplyJetpacks-2#13]
I am trying to use emergency hover with a Tier 3 jetpack, Energetic. The only thing I changed in the config was to make the tuberous jetpack obsolete.
I only wear the jetpack, fly up in the air and drop down. I die.
I now press the toggle button that I bound to apostrophe, there is no feedback so I guess it doesn't register..
Then I fly up and test again, same result, I die.

Forge version: forge-1.10.2-12.18.2.2105
SimplyJetpacks2 version: SimplyJetpacks2-1.10.2-2.0.3.14
EnderCore version: EnderCore-1.10.2-0.4.1.55-beta
Ender IO version: EnderIO-1.10.2-3.0.1.120_beta

**Comment by Tomson124** [comment]
Please always tell me which version of SimplyJetpacks2, EnderIO and EnderCore you are using. And if you have some other mods installed or even a modpack.

**Comment by Jomik** [comment]
I have a bunch of mods installed... Though I wouldn't have any idea why any of them would interfere with SimplyJetpacks.

- AmbientSounds v1.2.1 mc1.10.2
- AutoRegLib-1.0-2
- bdlib-1.12.2.14-mc1.10.2
- BetterAchievements-1.10.2-0.3.1.32
- BetterBuildersWands-0.6.5-1.10r138+8595fc7
- BetterFoliage-MC1.10-2.1.1
- BlockDrops-1.10.2-1.0.11
- Chameleon-1.10-2.1.7
- coroutil-1.10.2-1.1.9
- EnderCompass-1.9.x-1.2.3.2
- EnderCore-1.10.2-0.4.1.55-beta
- EnderIO-1.10.2-3.0.1.120_beta
- endertanks-1.10.0-1.4.2
- extraalchemy-0.3.0.3-release
- forestry_1.10.2-5.2.14.270
- gendustry-1.6.4.21-mc1.10.2
- GraveStone Mod 1.5.8
- Guide-API-1.10.2-2.0.2-45
- Improving Minecraft-1.12.1
- itemscroller-1.10.2-0.7.1
- jeibees-0.9.0.3-mc1.10.2
- jei_1.10.2-3.12.7.312
- journeymap-1.10.2-5.3.0b2-unlimited
- JustEnoughResources-1.10.2-0.5.3.62
- Mantle-1.10.2-1.1.1
- MCMultiPart-1.2.1-universal
- morebees-1.10.2-1.1.3
- multibeds-1.10.0-1.2.0
- multistorage-1.10.0-1.2.4
- OpenComputers-MC1.10.2-1.6.0.3-rc.1
- OpenGlasses-1.4
- OptiFine_1.10.2_HD_U_D1
- PersistentBits-1.10.2-1.0.5
- Quark-r1.0-56
- RandomThings-MC1.10.2-3.7.6
- RealisticItemDrops-1.0.7
- refinedstorage-1.1.2
- RTG-1.10.2-4.1.1.4
- ShadowMC-1.10.2-3.4.8
- shetiphiancore-1.10.0-3.3.2
- simplebarrels-1.10.2-2002-1.25h
- SimplyJetpacks2-1.10.2-2.0.3.14
- SleepingBag-1.10.2-1.3.0
- SoundFilters-0.9_for_1.9.4
- StorageDrawers-1.10.2-3.2.7
- TConstruct-1.10.2-2.5.6b
- TinkerToolLeveling-1.10.2-1.0.1
- ToughAsNails-1.9.4-1.0.11
- usefulnullifiers-1.2.1
- ViesCraft-2.5.0a-mc1.10.2
- Waila-1.7.0-B3_1.9.4
- WailaHarvestability-mc1.10.2-1.1.9
- zombieawareness-1.10.2-1.20

**Comment by Tomson124** [comment]
You simply just have the wrong version. The emergency hovermode is added to the mod in version 2.0.3.16
You still have 2.0.3.14. That is because I didn't push the build with the emergency hover mode the CurseForge yet as I didn't know how stable it is...
If you wnat to have the new version just download build 16 from the jenkins server: http://adf.ly/1eeGmt

**Comment by Jomik** [comment]
Updated to 2.0.3.17, now crashes me with an internal server error:
http://pastebin.com/wJsVMeY9
Figured I'd go with 17, as I'd like the dark soularium jetplate too..

**Comment by Tomson124** [comment]
First of all please post always the full crahs log not only the "crash at...." thing. Second I'm not sure as the crash log isn't complete but it seems that this problem is not directly related to my mod...

**Comment by Jomik** [comment]
Well, that is the whole crash log. Above that point, I only had this annoying console spam from RTG, because I use Forestry, and their saplings don't extend BlockSapling for some reason...

The crash only happens when falling with Emergency Hover on.
I started getting 
[17:10:42] [Server thread/DEBUG] [FML/]: The world 46bf32a1 (world) may have leaked: seen 130 times.
after upgrading to your version 17, after downgrading to 14, this doesn't happen.

Here's the "full" log. http://pastebin.com/Ti0w8WBC I had to cut the server startup and stop, as they made the file too long.

I realized as well, that the first crash I got was this: http://pastebin.com/FuaGkr4C
Which seems to be pointing directly at Simply Jetpacks.

**Comment by Tomson124** [comment]
The error in this link (http://pastebin.com/wJsVMeY9) is some weird thing with EnderIO as it cant find the TESLA API...
But the other error seems to be a error on my side, I used a client side only method to do something on the server... I will be doing a quick fix as soon as I am home.

**Comment by Tomson124** [comment]
I pushed a fix in the latest build on the jenkins server... Hope it fixes your crash, if it does just close this, if not tell me what happend exactly please :)

**Comment by Jomik** [comment]
Build is pending, awaiting executor for quite some time now :/
Also experiencing a weird client crash that I suspect happens on build 14, may be related to this. Issue is I get no crash log. But the crash only happens when I'm using the jetpack in or coming out of water. Client freezes and then java goes not responding and crashes.

**Comment by Jomik** [comment]
Seems to be working now. I am successfully not crashing while hover mode is being engaged! Great.
I experienced "User is about to die! Activating hover mode.", but it didn't activate hover mode (in time?) so I died. Only happened once and can be due to server lag, I suppose. Though, hosted on a local server.

**Comment by Tomson124** [comment]
I am aware of the thing that you sometimes because the hovermode activates too late... It was already a bug in the "old" SimplyJetpacks, I will see in the future how to improve that, but it is low priority for now as there are some gamebreaking bugs, too
