### ISSUE TITLE
invalid shaped ore recipe

### ISSUE THREAD

**Issue by kreezxil** [CyberdyneCC/SimplyJetpacks-2#131]
https://pastebin.com/cVyqR1uR

**Comment by Tomson124** [comment]
You have to install Redstone Arsenal so the error is fixed. I missed this recipe checking for RA to be installed. Will be fixed with next release.

**Comment by kreezxil** [comment]
The funny thing is that I didn't not enable Redstone Arsenal.

**Comment by Tomson124** [comment]
I know... I already mentioned that this is a bug as the recipe which is meant for players without RA is not activated.

**Comment by Tomson124** [comment]
Can you please send me the content of your config file?

**Comment by kreezxil** [comment]
http://paste.ubuntu.com/p/bRHn6H8T3S/
