### ISSUE TITLE
Particle customizers don't work with armoured jetpacks (EIO)

### ISSUE THREAD

**Issue by just-a-bird** [CyberdyneCC/SimplyJetpacks-2#14]
Particle customizers can't be crafted onto EIO armoured jetpacks, and crafting a customized jetpack into an armoured one erases its particle effect (replaces with Default).

- [WyldLife 1.2.2](https://minecraft.curseforge.com/projects/wyldlife/files/2340937)
- Minecraft 1.10.2
- Forge 12.18.2.2116
- SimplyJetpacks 2.0.3.14
- EnderIO 3.0.1.125 beta

**Comment by Tomson124** [comment]
I know those a things I am aware of but don't have much free time at the moment, but I will fix those things as soon as possible

**Comment by Tomson124** [comment]
This is fixed in the latest dev build which you can find here: [Jenkins (Adfly)](http://adf.ly/1eeGmt)
