### ISSUE TITLE
Jetpacks not recharging

### ISSUE THREAD

**Issue by number65259** [CyberdyneCC/SimplyJetpacks-2#141]
Desync similar to #72 but not cosmetic and affecting all jetpacks. When fuel reaches 0%, player loses flight. Appears to be a desync in actual rf/t values/capacitance sources.

Modpack is project ozone 3. It is particularly noticeable there due to the increased rf/t requirements set in the jetpack cfg. Jetpack can be covered by a huge capacitor with high throughput but you'll only get a few seconds of flight unless you do something that forces a sync like toggling hover, tapping spacebar with hover off, picking pack up in your inv, using an item that forces sync like a wireless grid, toggling capacitor, etc. Draining the jetpack a bit with no capacitor activated, then activating a cap will allow it to charge as expected. Upon reaching 100%, desync occurs and jetpack starts draining to zero.

**Comment by number65259** [comment]
Experienced with certain caps as well. This is probably better reported on the modpack page.

**Comment by Tomson124** [comment]
This indeed sounds weird, but could also be the extreme config values that PO3 sets (I am playing the pack myself, too.) Maybe you can provide a video or a detailed guide on how to reproduce the issue, as I am not really getting it by your description.

**Comment by number65259** [comment]
Did some testing.

Leadstone Jetpack, Resonant Capacitor which should cover the inflated 1,000 rf/t np. Worth noting that the cap still drains along with the jetpack, which makes sense due to the rapid recharge/apparent desync. RF is going somewhere, just not the jetpack during flight: 
https://imgur.com/a/LzZLUp8

Hover mode off, tapping spacebar. Watch fuel values in top left. This is the only effective way I could fly early on due to small jetpack buffer and inability to charge during active thrust/hover with a capacitor from thermal:
https://imgur.com/a/jNOr40Z

It gets weirder. Draconic cap instead of resonant, vid below. Jetpack drains the capacitor without issue:
https://imgur.com/a/kLdREvn

This is what made me want to report on PO3 due to possible cross-mod interaction. When a spectre charger is introduced, draconic capacitor experiences a similar desync instead of the jetpack? Notice the instant sync behavior when picking up the cap, same as the jetpack with capacitor from thermal:
https://imgur.com/a/q8tbS3v

Using certain other RF-powered items that charge from a cap will resync everything until the capacitor or jetpack is fully charged, at which point they will desync again. With a railgun as the trigger for forcing sync. Flight drains cap, spectre charger doesn't work until railgun is fired, cap recharges to 100% then starts draining again :
https://imgur.com/a/iSl8Pyb

With wireless crafting terminal as trigger for forcing sync:
https://imgur.com/a/mwuvgj4

Same desync at 100% charge on a jetpack, no capacitor used, spectre charger only:
https://imgur.com/a/WDqn9Gg

**Comment by Tomson124** [comment]
Very very weird... Looks almost like it would be an issue with RF-API itself. I will look into it.
Thank you for the really detailed overview and even videos, that is really helpful.
I hope I don't ask too much if I ask you to test the behavior with charging without my jetpacks but with e.g. the Dark steel chestplate or any other "chargeable" armor. Just to see if it is an API thing in general or my mod. Because as far as I know are Draconium Evolution and EnderIO not using the RF-API directly, as I am currently still doing, which could cause problems. But only if you have free time and will to do it.
