### ISSUE TITLE
Client crashes when trying to charge Wireless crafting Terminal with Flux-Infused JetPlate

### ISSUE THREAD

**Issue by Arudinne** [CyberdyneCC/SimplyJetpacks-2#143]
Hello,

Recently the server I am playing on updated it's mod pack to All The Mods 3 - Remix 1.5.0,

After updating I encountered several issues where I would get disconnected. Following that anytime I tried to rejoin I would get disconnected immediately and the only way to resolve my issue was to restore my playerdata from a backup.

It looks like anytime I selected my Wireless Crafting Terminals 2 Wireless Crafting Terminal on the hot bar my client would disconnect me from the server and state "Internal Server Error"

Working with one of the admins we traced the error the charging function of my Flux-Infused Jetplate. Once I turned the charger off, I stopped having the issue. Below should be the relevant log data.
Full crash log:
https://pastebin.com/FG0XAgYd

**Comment by Tomson124** [comment]
From what version did the server update to 1.5.0? Just to see which mods were updated and what changed that this issue arose.
And just as a quick note, using Pastebin or Github Gist for log files makes the issue a lot more clear.

**Comment by Arudinne** [comment]
We updated from All The Mods 3 - Remix 1.3.0 to All The Mods 3 Remix 1.5.0

https://github.com/AllTheMods/ATM3-Remix

Not sure if I noted it above, but this issue did not occur prior to updating.

**Comment by Tomson124** [comment]
New version wich fixes this, was uploaded to Curse. Is currently under review.
I close this issue now, if the problem shoul still persist feel free to reopen it.
