### ISSUE TITLE
Crash regarding to redstone repository

### ISSUE THREAD

**Issue by 7thCore** [CyberdyneCC/SimplyJetpacks-2#144]
After updating my server to the latest mods, players are getting crashes regarding to redstone repository wich isn't installed in our modpack.

Here is the full error log:
https://pastebin.com/YK9gDk71

**Comment by Tomson124** [comment]
Which mods did you update? Do you have a changelog? Can you provide more information on how to reproduce the crashes? E.g. What did you do before it crashed? Does it happen randomly or when using a jetpack or even use it to charge another item?

**Comment by Tomson124** [comment]
#143
