### ISSUE TITLE
Jetpack Mode Overlay

### ISSUE THREAD

**Issue by maonya** [CyberdyneCC/SimplyJetpacks-2#146]
The Jetpack Mode Overlay covers my Optifine FPS Reader, thus causing them to overlap and be difficult to read. Please fix asap.
![2019-10-26_18 43 48](https://user-images.githubusercontent.com/56891570/67628334-b9b80e80-f820-11e9-91b3-b2205daf185f.png)

**Comment by Tomson124** [comment]
There is nothing to fix in the mod. As there is already a config option in the simply jetpacks client config, where you can adjust the position of the jetpack Overlay.
And compatibility with Optifine is considered not supported for most mods anyway.
