### ISSUE TITLE
Cannot craft final pieces for Either Jetplate

### ISSUE THREAD

**Issue by Solverbolt** [CyberdyneCC/SimplyJetpacks-2#150]
Playing on MC Eternal 1.3.5 latest stable version. 

Myself and at least 5 others have tried to make the last parts, the Elevation Unit/Flight Control unit (we tried both sides to be sure).  Neither is working.  I can craft the empty flight control unit, but when i attempt to put a soul vial with a bat into the Soul Binder, it wont accept the flight control unit, and vice versa.  

As for the Glowstone Elevation unit, it does have an output, it lets me add the parts to a crafting grid, but the system does not recognize the parts as valid, so does not create an output item

**Comment by Tomson124** [comment]
Sorry for the late response.
Is the recipe showing in JEI?
Did you try crafting it without the other mods in the pack? Could be a recipe conflict.

**Comment by Solverbolt** [comment]
yeah, we found the conflict.  Vampirism Mod was the issue, as it replaced all the bats in the world for its own, and they are incompatible with your mod
