### ISSUE TITLE
[2.0.3.19] Possible crash on joining server

### ISSUE THREAD

**Issue by SPMoo66** [CyberdyneCC/SimplyJetpacks-2#16]
A player of ours joined our server and was met by a crash. Oddly, he was the only one to have crashed, and it only happened to him once.

http://pastebin.com/qaX0qZv5

Looks like it could be related to the last one...? Not too sure.

https://github.com/CyberdyneCC/SimplyJetpacks-2/issues/12

**Comment by Tomson124** [comment]
Please try the new version 2.0.3.26 for testing on your server and tell me if there are still problems. If there are just open another issue I will close this one and #12 for now.
