### ISSUE TITLE
[2.0.3.23] Dark Soularium Jetpack recipe

### ISSUE THREAD

**Issue by tacogerbil** [CyberdyneCC/SimplyJetpacks-2#17]
I HAD a Vibrant Jetpack.. I tried making a soularium in the past... No recipe.  Today, I updated the mod on my personal server to your latest one SimplyJetpacks2-1.10.2-2.0.3.23 using forge forge-1.10.2-12.18.3.2185-universal........ I logged in and my jetpack is now a Dark soularium jetplate?!?!?

**Comment by RealGrep** [comment]
I can definitely confirm I also have no recipe for the dark soularium jetplate. And though I didn't have the issue with the jetpack becoming another tier this update, I did have that happen a few updates ago. I had the tier 1, and it turned into a dark soularium jetplate.

Might be some deeper issue at work here. Other than that, it seems to work well, and the dark soularium jetplate works fine if I spawn it in. I can probably get it to be craftable with a simple MineTweaker recipe, but definitely an issue there. I assumed you just hadn't got to it (and let you know in the MMD discord, but you never really came back, so I assume you missed it).

**Comment by tacogerbil** [comment]
I've read in earlier posts that is all still in work...  So not having a
recipe want surprising.  That alone kept me from reporting it as a bug.. lol

**Comment by Tomson124** [comment]
I hate it that I always have to say it again... 
The whole mod is still WIP and every build you download form CurseForge are just the buildartifacts from my jenkins server, I am just evalutating how stable the build is and if it runs mostly fine I upload it to Curse. So there WILL be things missing or be even broken, that is just how it is.

For this particular case: For those of you who know the "old" recipe for the dark soularium jetpack from the original SimplyJetpacks, it includes a flux pack, which I didn't got to update yet. So there will be no recipe for it for now.

Regarding the jetpack change thing, this is very likely the result of the Item meta change I did in the latest build. But I say it again this mod is WIP! Things can change, be removed, break or even work as expected, everything is possible.

**Comment by Nuinethir** [comment]
Any update on this? Would love to be able to upgrade to the final tier of jetpacks.

**Comment by Tomson124** [comment]
I am almost finished with implementing the fluxpacks, and if I am I will reenable the recipe for the Dark Soularium Jetpack and release a new version on Curse. I will close this issue when that happens, so you know that it is fixed.

**Comment by ToadsworthLP** [comment]
@Tomson124 Could you please notify me when the Fluxpacks are finished? As soon as they are I'll start working on the TE-based jetpacks as the Thermal* mod's release is at maximum a few days away :)

**Comment by Tomson124** [comment]
"Fixed" in latest version: 2.1.0.39
