### ISSUE TITLE
server hang in void worlds at extreme y levels

### ISSUE THREAD

**Issue by jdratlif** [CyberdyneCC/SimplyJetpacks-2#18]
If I use a jetpack and go either really high or really low and come back, the server crashes. In a single player world, minecraft completely hangs until I force close it. On a server, I can logout and log back in and see a crash with the server.

http://pastebin.com/LVa02Q5X -- crash log

MC 1.10.2
Forge 2185
Simply Jetpacks 2 2.0.3.23
EnderCore 0.4.1.61
EnderIO 3.0.1.141
JEI 3.1.3.6.391

BetterBuildersWands 0.8.0r170
YUNoMakeGoodMap 6.1.0.26

I've been trying to test mob spawning buildings, and I was using the jetpack to hover and the wand to build with. YUNoMakeGoodMap is to make a void world. I wasn't able to easily duplicate this in a normal world, but in a void world, it's very easy.

Steps to reproduce:

Create void world with YUNoMakeGoodMap (tree, single grass, Skyblock 2.1, whatever).
Use JEI to get Creative Jetpack
Go really high (like y positive 240)
Fall to what should be your death.
Press F3 to find out you've fallen much past the end of the world and the server is hung. You can't get more items from JEI, jettison things from your inventory, break blocks, or anything else really as the server is hung.

More than happy to help test and provide whatever else you might need.

Minecraft Server is on Gentoo Linux with IcedTea Java 8 111 64-bit.
Minecraft Client is on Windows 10 with Java 8 u111 64-bit.

**Comment by Tomson124** [comment]
That's what I call a good error report ;) Thanks.

I will have a look at it as soon as possible. Probably has something to do with the missing ground which is part of calculating the flying.

If you have time it would be very nice if you could try to reproduce the error with a jetpack that has no emergency hover (e.g. a tier one jetpack) As it could be related to that, too.

**Comment by jdratlif** [comment]
It certainly seems related to the missing ground. If I use a tier 1 jetpack, or disable emergency hover mode, I don't seem to experience the issue.

You don't even need to go to a high y level. Simply don a creative jetpack and jump off the starting platform and it will occur.

For now though, I can disable emergency hover mode.

Thanks.
