### ISSUE TITLE
[1.10.2] EnderIO Charging Incompatibility

### ISSUE THREAD

**Issue by oitsjustjose** [CyberdyneCC/SimplyJetpacks-2#27]
Minecraft Version: 1.10.2

MinecraftForge Version: 12.18.3.2239

SimplyJetpacks Version: 2.1.0.39

Other Mods: [Modlist](http://puu.sh/v1js4/359fb30918.txt)
___

**Issue:**

So, it seems as though the EnderIO Capacitor Pack and Jetplate don't care at all about charging EnderIO Items. Any EnderIO "RF" receiving item (armor, tools, etc) will _not_ receive power from the capacitor pack. Generic RF receiving items like Redstone Arsenal items (including armor), Actually Additions items, and others will happily receive energy. 

[GIF Demonstration of Bug](http://puu.sh/v1jUW/236a1a15a3.gif)

___

**Proposed Solution:**

Best thing I can think of is if SimplyJetpacks does what many other "RF" mods of 1.10.2+ have been doing, and that's implement ForgeEnergy alongside the RF API (it's also worth mentioning that CoFH has updated the RF API officially to 1.10.2, so you may want to look at updating it as well - that might resolve the issue).

___

Let me know if I can help! Thanks!

**Comment by Tomson124** [comment]
That's what I call a bug report :D Thanks for the huge amount on info. I didn't notice that the RF API was updated and the last time I tried if charging is a few months ago...
Regarding the ForgeEnergy, I have planned on implementing it (TESLA API, too) But I am working full time so my time (and my java knowledge) are very limited. I will try the RF update and see if it fixes it.

**Comment by oitsjustjose** [comment]
> That's what I call a bug report :D

As a developer, it's my duty to follow the golden rule of bug reports - do unto others and whatnot.
Anyways - totally understand the full-time-job dilemma. Get to it when you can!

**Comment by Tomson124** [comment]
Updating didn't fix it but after some research I found this: https://github.com/SleepyTrousers/EnderIO/issues/3992
"EnderIO items no longer accept RF - only Forge Energy or Tesla.
But EnderIO conduits and machines still support RF when the RF API is available (it is no longer bundled)." - MatthiasMann
So you will have to wait until I implemented either ForgeEnergy or TESLA...

**Comment by oitsjustjose** [comment]
Hey, that works for me!

_Low-key hoping you choose ForgeEnergy since it's already included, and 90% of mods support it if not exclusively._

Again, thanks for your help!

**Comment by Tomson124** [comment]
Fixed in latest verison: 2.1.1.43 available on Curse (after reviewing)
