### ISSUE TITLE
potato jetpack "Not working"

### ISSUE THREAD

**Issue by TheDWPCer** [CyberdyneCC/SimplyJetpacks-2#29]
Version:2.0.3.26 "Beta"

No crash log

in the old simple jetpacks if you used the potato jetpack it would explode in the best way possible 

this might be a bug... or you something planned

**Comment by Tomson124** [comment]
This is more or less intended... Right now this "april fool" is not a high priority on my list, I am even thinking about removing it completly. I am aware of potato jetpack not functioning simply as I didn't update it completly to 1.10 yet...
