### ISSUE TITLE
Jackpack energy is not reduced

### ISSUE THREAD

**Issue by Geosearchef** [CyberdyneCC/SimplyJetpacks-2#31]
When flying with a conductive iron jetpack, which was charged in an EnderIO capacitor, the jetpack energy stays at a 100 %. Lastest version (665e69b) is being used.

**Comment by Drock1994** [comment]
I am having the same issue

**Comment by Tomson124** [comment]
Can you please see if the bug is happening in the older version, too?

**Comment by Tomson124** [comment]
Fixed in latest version 2.1.2.47 on Curse
