### ISSUE TITLE
"Lag" toggling jetpack and hover on/off when bound to mouse4/mouse5

### ISSUE THREAD

**Issue by shintol** [CyberdyneCC/SimplyJetpacks-2#32]
Whenever I have "toggle jetpack" and "toggle hover" bound to mouse4 or mouse5 the toggle is delayed or never toggles until I press either the keybind to go up or down.  Once done it immediately toggles.  This seems to only effect the mouse buttons, as it works immediately when the toggles are bound to keyboard keys.

**Comment by Tomson124** [comment]
Maybe it has to do with my method of gathering the right keybind which is not made for using the mouse buttons, I will have a look at it.

**Comment by Tomson124** [comment]
After some testing I can tell you it is no "lag". When you hit the bound mousebutton it will not do anything before you hit any key on the keyboard... It has something to do with the refreshing. That same issue exists in EnderIO, too. I will see what I can do, but for now just don't use the mousebuttons as keybinding.
