### ISSUE TITLE
[1.10.2] Jetpack energy isnt being taken when jetpack is used..

### ISSUE THREAD

**Issue by MJRLegends** [CyberdyneCC/SimplyJetpacks-2#35]
Hello,

So i charged my Tier 1 Conductive-Iron Jet-pack using a Mekanism Wind Generator, and when using the Jet-pack i could have infinite flying as the energy wasn't decreasing.

Forge: 12.18.3.2316
SimplyJetpacks-2: 2.1.2.53
Mekanism: 9.2.2.301

If you need any more information please just ask i will be happy to provide some :D

**Comment by MJRLegends** [comment]
Ok, after more testing it seems to be when charged with anything and seems to be any jetpack not just the  Conductive-Iron Jet-pack, would you like a mod list?

**Comment by MJRLegends** [comment]
ok i downgraded to 2.1.1.47 and it seems to be working there :D

**Comment by Tomson124** [comment]
Version 2.1.3 is currently under review by Curse, in about 5 or 10 minutes it should be available. It fixes the issue.
You can also download it here right now from my jenkins-dev-server: http://adf.ly/1eeGmt

**Comment by MJRLegends** [comment]
Thanks great work :)
