### ISSUE TITLE
Missing Texture in Thermal Expansion Jetpacks

### ISSUE THREAD

**Issue by AndreiTS** [CyberdyneCC/SimplyJetpacks-2#36]
minecraft: 1.10.2
forge: 12.18.3.2422
simplyjetpacks: 2.1.3.55

![2017-07-24_19 53 50](https://user-images.githubusercontent.com/13489837/28631170-b7fad894-7202-11e7-940a-18c216cb13cf.png)
![2017-07-26_12 59 34](https://user-images.githubusercontent.com/13489837/28631172-b7fdd026-7202-11e7-89e2-8aef10142b55.png)
![2017-07-26_13 01 16](https://user-images.githubusercontent.com/13489837/28631174-b7ff1530-7202-11e7-97e3-05dde981143f.png)
![2017-07-26_13 01 22](https://user-images.githubusercontent.com/13489837/28631173-b7fe3ab6-7202-11e7-998a-a0b5041a2e0e.png)
![2017-07-26_13 01 29](https://user-images.githubusercontent.com/13489837/28631176-b85624ec-7202-11e7-80e4-17f8cf765df3.png)
![2017-07-26_13 01 42](https://user-images.githubusercontent.com/13489837/28631177-b92daca0-7202-11e7-8a68-de7a20407ab8.png)
![2017-07-26_13 01 47](https://user-images.githubusercontent.com/13489837/28631171-b7fb2f38-7202-11e7-82c9-92611f163d21.png)

**Comment by mgdgfbhevdyeh** [comment]
I did not see any TE jet backpack texture in the source code
It seems that the problem is from:https://github.com/CyberdyneCC/SimplyJetpacks-2/commit/ecef7844fab2b9d833e41a323c1ae0dfdcef45ea
isn't have TE textures in source:https://github.com/CyberdyneCC/SimplyJetpacks-2/tree/1.12/src/main/resources/assets/simplyjetpacks/textures/armor
but still have TE's texutures in here:https://github.com/CyberdyneCC/SimplyJetpacks-2/tree/1.12/resources_old/armor%20(TE)
I think just need readd it

**Comment by Tomson124** [comment]
Please guys read the changelog provided on Curse before or when downloading a new version.
There I explicitly stated that the TE implementation is not finished yet... I am currently redoing the textures, too, I will add them when they are finished.

**Comment by igams** [comment]
Really dissapointing that textures for Thermal Dynamics still haven't been implemented. Does anyone know if it would be possible to use the textures from the original mod as a fix?

**Comment by MainFreak** [comment]
@Tomson124 Reminder that this is still not fixed. The assets seem to be present in the 1.12 version so I have no idea why they aren't in the 1.10 one,

**Comment by Tomson124** [comment]
Because they are not implemented yet in the 1.10 version. And maybe won't be in the future, too, as I am concentrating on the 1.12 version right now.

**Comment by legoboy0109** [comment]
I would like to add, as a mod developer myself, updating the 1.10.2 version wouldn't take a huge amount of work if 1.12 is already done. I use 1.10.2 to play modded, because some of the mods I use haven't been updated to 1.12 yet. I would like to see the TE implementation in 1.10 finished.

**Comment by thundr** [comment]
If @Tomson124 you want to backport fixes to 1.10 reopen this, but IMO 1.12 is the only supported version atm.
