### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by philipp8101** [CyberdyneCC/SimplyJetpacks-2#37]
Missing recipes for 
 -Flux-Infused Jetplate
 -Fluxed Thruster

in MC 1.10.2
with Forge 12.18.3.2422
    CodeChickenCore-1.10.2-2.4.1.102
    CodeChickenLib-1.10.2-2.5.9.283
    CoFHCore-1.10.2-4.1.11.16
    EnderCore-1.10.2-0.4.1.66
    EnderIO-1.10.2-3.1.193
    jei_1.10.2-3.14.7.420
    SimplyJetpacks2-1.10.2-2.1.3.55
    ThermalDynamics-1.10.2-2.0.10.16
    ThermalExpansion-1.10.2-5.1.9.21
    ThermalFoundation-1.10.2-2.1.5.12

**Comment by Tomson124** [comment]
Tehy are not missing...  they are just WIP, I wrote this in the changelog please read it before posting issues

**Comment by philipp8101** [comment]
My bad didnt read the changelogs for the non latest version. sorry
