### ISSUE TITLE
Missing textures in 1.12.1

### ISSUE THREAD

**Issue by IcedReaper** [CyberdyneCC/SimplyJetpacks-2#39]
Hi,

I just wanted to inform you that it seems that there are still textures missing.
Here is the log from the Gameoutput:

`
10:45:18    TEXTURE ERRORS  main    error     domain simplyjetpacks is missing 22 textures
10:45:18    TEXTURE ERRORS  main    error       domain simplyjetpacks has 2 locations:
10:45:18    TEXTURE ERRORS  main    error         mod redstoneflux resources at C:\Users\IcedReaper\Documents\Curse\Minecraft\Instances\simplyJetpackTest\mods\SimplyJetpacks2-1.10.2-2.1.3.9.jar
10:45:18    TEXTURE ERRORS  main    error         mod simplyjetpacks resources at C:\Users\IcedReaper\Documents\Curse\Minecraft\Instances\simplyJetpackTest\mods\SimplyJetpacks2-1.10.2-2.1.3.9.jar
10:45:18    TEXTURE ERRORS  main    error   -------------------------
10:45:18    TEXTURE ERRORS  main    error       The missing resources for domain simplyjetpacks are:
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustereio2.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/jetpackvanilla3.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thruster_te1.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustervanilla2.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/armorplating.eio.2.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustereio5.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustereio4.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/unitflightcontrol.empty.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/jetpackvanilla1.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/reinforcedgliderwing.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/armorplating.eio.3.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/ingotdarksoularium.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrusterte5.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/unitflightcontrol.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/armorplating.eio.1.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustervanilla1.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustereio1.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustervanilla3.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/thrustereio3.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/armorplating.eio.4.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/jetpackvanilla2.png
10:45:18    TEXTURE ERRORS  main    error         textures/items/leatherstrap.png
`

MC-Version: 1.12.1 / 1.12.2
Forge: 14.22.0.2474 / 14.23.0.2503

Thanks,
IcedReaper

**Comment by Tomson124** [comment]
I am aware of that, but other things are more important at the moment, and the versions are still pre alpha status.

**Comment by IcedReaper** [comment]
Alright, no worries, just wanted to inform you incase you didn't know.
