### ISSUE TITLE
No armor value for jetpacks

### ISSUE THREAD

**Issue by xenoflot** [CyberdyneCC/SimplyJetpacks-2#42]
Hi,

I noticed just now that I'm not getting any armor value displayed when I don my Reinforced Jetpack, so I did a little spawning and testing.

Creative - none
EnderIO (without plate) - none
EnderIO (with plate) - yes, but only if they have some charge
Thermal Expansion - none
Flux-Infused - yes, but only if it has charge

This does stand to reason as only the EIO+Plate actually adds some armour plating however, the tool-tip on all of these reports that it gives 6AC.

So two "bugs":
1. The JEI tooltip is incorrectly reporting 6AC (A JEI problem?)
2. IMO the armour value should be applied even if the jetpack has no power.

Thanks very much for a mod that's given me lots of fun over the years!
Cheers

Playing current (20171012) ver of FTB Beyond 1.10
MCP 9.19
FML 8.0.99.99
Forge 12.18.3.2422
AE2 rv4-stable-1
SJ2 2.1.3.55

**Comment by Tomson124** [comment]
Regarding 1. It's not JEI showing those values, it's vanilla minecraft. I will fix this.
For 2. I think that is actually a good idea, I will change this for the upcoming 1.12 builds, but probably not for the 1.10.2 ones, I will see...

**Comment by xenoflot** [comment]
Fabbo!

**Comment by Tomson124** [comment]
First thing implemented in dev branch: 0bd7243e2efbb57b8f255386de0f5ae4bde378f8
