### ISSUE TITLE
Can't craft Flux Infused JetPlate Tier5 (simply-jetpacks-[1.10.2]-2.1.3.58)

### ISSUE THREAD

**Issue by freaki2010** [CyberdyneCC/SimplyJetpacks-2#43]
Hello Tomson124 I can't craft the Flux Infused JetPlate because there is only one recipe with this JetPlate where i can change the Particle. 
Can you pls help me with that?

**Comment by Tomson124** [comment]
The recipe is not implemented yet...

**Comment by freaki2010** [comment]
When will it be implemented?

**Comment by Moobien** [comment]
Instal Redstone Arsenal as a workaround
