### ISSUE TITLE
Any chance of a 1.11.1 version?

### ISSUE THREAD

**Issue by steampunko** [CyberdyneCC/SimplyJetpacks-2#44]
Any chance you could make a version for 1.11.1?

**Comment by Tomson124** [comment]
Probably not as 1.12.2 ist the latest and most stable (Forge) version.
I'll probably do a small backport of the ThermalExpansion jetpacks to 1.10.2, but as my time is very limited I probably won't do a 1.11.x version. And even if I do, it will be after I finished the 1.12.x one

**Comment by Tomson124** [comment]
As already mentioned before there won't be a 1.11.x version as most of the mods are moving forward to 1.12.2 and I will not be moving backward with the mod either.
