### ISSUE TITLE
Uncraftable items? 1.12.2-2.1.3.17

### ISSUE THREAD

**Issue by Plaah007** [CyberdyneCC/SimplyJetpacks-2#46]
Tried to craft Flux-Infused JetPlate but can't put Cryotheum Coolant Unit (Empty) or Glowstone Elevation Unit (Empty) in the Fluid Transposer to make the filled ones. They don't have recipe in JEI (the filled ones).

Bronze Armor Plating, Invar Armor Plating and Enderium Armor Plating don't have textures and recipe in JEI.

**Comment by Tomson124** [comment]
Like in the last changelog already mentioned it is not possible to craft the Jetplate yet as the components are not working yet as I have to redo the complete integration for Thermal Expansion as they also did a complete rewrite of their code.
