### ISSUE TITLE
[1.12.2] Missing Reinforced Flux Pack

### ISSUE THREAD

**Issue by TheLimePixel** [CyberdyneCC/SimplyJetpacks-2#47]
Following TE's machine tiers, the mod is missing a Reinforced Flux Pack. The Hardened one also looks like it'd be Reinforced and it uses a Reinforced Cell in its recipe, so there seems to be a mismatch here.

**Comment by Tomson124** [comment]
I forgot to change the name for the tier 2 jetpack. Is fixed in version 2.2.1.19. As many said 4 tiers are to much, I reduced the amount to 3, a leadstone, reinforced and resonant one. (Maybe in the future it will be a single one with upgrades...)

**Comment by TheLimePixel** [comment]
It still hasn't been changed.

**Comment by Tomson124** [comment]
Thanks for the headsup, just uploaded another build of the current version, in this it should be fixed.
