### ISSUE TITLE
[1.12.2] Armored Flux Packs Have No Recipes

### ISSUE THREAD

**Issue by TheLimePixel** [CyberdyneCC/SimplyJetpacks-2#49]
The title says it all.

**Comment by dash16** [comment]
I noticed this too when trying to craft the Flux-Infused JetPlate, as the Resonant Flux Pack (armored) is a required component.  Looks like both the Reinforced Flux Pack (Armored) and Resonant Flux Pack (Armored) can't be crafted.

Edit: Using 1.12.2-2.2.1.20
