### ISSUE TITLE
Hover Mode Please? :)

### ISSUE THREAD

**Issue by Darkosto** [CyberdyneCC/SimplyJetpacks-2#5]
Hey @Tomson124 !

Thank you again for your hard work. I spent a bit of time on stream yesterday working through some of the jetpacks and just checking them out. So far, everything seems on track! I didn't know what you had on your to-do list, so instead of making a bunch of issue reports I thought I'd ask if you want me to message you in another way? 

Aside from that, do you plan on making hover mode available soon? It's one of the biggest upsides to the late tier jetpacks and I would really love it :D 

Thank you!!
Darkosto

**Comment by Tomson124** [comment]
Wait... hover mode should be a feature already :/ That is weird, does it not work?

**Comment by Darkosto** [comment]
Maybe I'm turning it on incorrectly then? I tried using the keybinds on the tier 1-4 jetpacks and no luck :( Does it need anything new to activate it?

**Comment by Tomson124** [comment]
Like I wrote, it is an alpha (or more just dev builds) which happen in the progress of coding... all Jetpack features should work with the Creative one at the moment, I didn't tested it with the EIO Jetpacks as those are still WIP...

I will do something for the suggetions, probably on my website or something else, for now just message me on Discord or Twitter.
Discord: https://discord.gg/HhhWRXd

**Comment by Darkosto** [comment]
Oh, it's definitely not a problem at all. I completely understand this is an alpha build :)

I'm just trying to help out with testing if needed and let you know if/when anything pops up. I apologize for creating the issue!

Thank you again for your help and responses

**Comment by RealGrep** [comment]
Just related to issue #3, I assume.
