### ISSUE TITLE
[1.12.2] Jetpack armor issue

### ISSUE THREAD

**Issue by PainWarrior** [CyberdyneCC/SimplyJetpacks-2#53]
I cant seem to remove the invar armour plate off my electum jetpack in direwolf 20's pack ive tried shift right clicking and shift left clicking and placing in crafting grid like it used to work and nothing i am not sure if this is a mod or a mod pack issue but i dont want to make another jetpack when i have one to upgrade already ty for any help ahead of time.
![2018-01-11_19 16 10](https://user-images.githubusercontent.com/35354016/34855178-ed3c079a-f703-11e7-8004-e9dd96b2a181.png)

**Comment by Tomson124** [comment]
I am aware of the problem and it is already fixed in the latest dev version. The fix will be in the next release on Curse, too, which will be (hopefully) this weekend.

**Comment by choekstr** [comment]
Any word on a release with this fix in it?  Currently hit this bug in Forever Stranded: Lost Souls pack

**Comment by Tomson124** [comment]
Fix will be published today, but no idea when the pack author updates the mod for you.
