### ISSUE TITLE
[Suggestion] Mekanism Variant?

### ISSUE THREAD

**Issue by ixanza** [CyberdyneCC/SimplyJetpacks-2#58]
I know what you're thinking, Mekanism already has a jetpack. But the ones offer here have so much more control and versatility that overshadows the Mek Jetpack. Would you consider this?

**Comment by thundr** [comment]
@Tomson124 Do you want to give a final yes/no on this idea? So we can close or add to TODO.

**Comment by Tomson124** [comment]
I don't really like the idea as Mekanism's dev spent a lot of effort on the jetpacks (maybe they are not as controllable or anything, but they are a one of a kind piece). Maybe we close it for now, and I will have a small chat with Mekanism's dev what he thinks about it.
