### ISSUE TITLE
Unable to remove plating

### ISSUE THREAD

**Issue by saeldion** [CyberdyneCC/SimplyJetpacks-2#59]
I'm trying to upgrade my Hardened Jetpack (Armored) to the next tier (Reinforced Jet Pack). The recipe for this requires that I use a Hardened Jetpack (Non armored). I'm however unable to remove the plating from my existing jetpack.

I don't know if I'm supposed to be able to remove it. But I think I remember removing the plating in an earlier version (when playing FTB Infinity).

I've tried holding it and shift+rclick and I've tried it in a workbench. Can't find any recipe for removing it.

I'm playing with: SimplyJetpacks2-1.12.2-2.2.1.20.jar (in Direwolf20 1.12 pack v1.8.0)

**EDIT:**
Found #53 after I posted refering to the same issue. This can be closed as it seems solved in a newer version.

**Comment by Tomson124** [comment]
Indeed this is already fixed, but not updated in the Direwolf20 pack.
Please just update it yourself until the modpack is updated. I'll try to get in contact with Direwolf or his modpack maintainer and tell them about the update.
