### ISSUE TITLE
[2.0.2.9] "Format error" appears in jetpacks' JEI entries

### ISSUE THREAD

**Issue by SPMoo66** [CyberdyneCC/SimplyJetpacks-2#6]
Appears twice on every jetpack entry

https://u.pomf.is/eevszf.png

Oops, guessing you already fixed this based on the dev branch...

**Comment by Tomson124** [comment]
Yeah, I noticed it right after uploading the file to curse ^^
It is already fixed in the dev branch like you said, you get the latest version (with the fix) on [jenkins](http://adf.ly/1eeGmt).
But thanks for reporting bugs :)
