### ISSUE TITLE
can't craft jetplate with particle customizer?

### ISSUE THREAD

**Issue by seebs** [CyberdyneCC/SimplyJetpacks-2#60]
quite possibly not your fault.

SimplyJetpacks2-1.10.2-2.1.3.55.jar

this is in a SkyFactory3 modpack. There's recipes for crafting the jetpacks with particle customizers, but not for crafting the jet*plate* with particle customizers.

**Comment by Tomson124** [comment]
Probably is my fault, but 1.10.2 version of the mod is no longer supported by me. Maybe I will push a last fix update for it if I have time, but currently I am concentrating on the 1.12.2 version. And quite busy with work and learning for exams, too.
