### ISSUE TITLE
[1.12.2] Add check for Mod when compat is enabled in config

### ISSUE THREAD

**Issue by khionu** [CyberdyneCC/SimplyJetpacks-2#62]
It would be recommended to either throw a clear error, specify the enabled compat as a dependency, or ignore the compat if the mod is missing. I would personally recommend the latter. As is, it just throws when trying to add the recipe, and without a clear message.

**Comment by Tomson124** [comment]
For which "setup" did this happen? Which mods did you have installed and which version of SimplyJetpacks 2? As it should only load recipes when the mod is loaded and the config option is set to true.

**Comment by thundr** [comment]
This is not repro, closing unless you can provide more info.
