### ISSUE TITLE
Unexpected error 1.12

### ISSUE THREAD

**Issue by AltStuff** [CyberdyneCC/SimplyJetpacks-2#66]
SimplyJetpacks2-1.12.2-2.2.2.28

[Crash report](https://pastebin.com/raw/mmMX82v0)

**Comment by Tomson124** [comment]
Could you please describe what you did before the crash? So I can try and reproduce the error.

**Comment by Tomson124** [comment]
Any news on my question?

**Comment by thundr** [comment]
Closing from inactivity. Reopen if you have more to share.
