### ISSUE TITLE
Problem due to the SimplyJetpacks-2? [Crush]

### ISSUE THREAD

**Issue by HurtsAsHell** [CyberdyneCC/SimplyJetpacks-2#67]
I'm creating a modpack, I installed the latest versions of simply jetpacks 2
Today this problem arises that, by removing all the mods, adds today, continues to recur; What can I do?
The mods that have the crush are:

| UCE | thermalexpansion | 5.3.10 | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None |
| UCE | simplyjetpacks | 2.2.2.28 | SimplyJetpacks2-1.12.2-2.2.2.28.jar | None |

Have you already encountered the problem?
Do you know how to solve it?

All logs, crush reports[https://www.dropbox.com/s/7nck4yqlje1ldf8/Crush.zip?dl=0](url)

Sorry for my bad english but i use google traslate.

**Comment by Tomson124** [comment]
The link you posted is not working, please just upload the crash log to e.g. pastebin and post the link here.

**Comment by HurtsAsHell** [comment]
okay; sorry for the wait, I found the problem; thanks anyway
