### ISSUE TITLE
Mod adds Fluxed Armor Plating despite Redstone Arsenal being installed

### ISSUE THREAD

**Issue by 347Online** [CyberdyneCC/SimplyJetpacks-2#68]
As the title says, despite having Redstone Arsenal installed, the mod still adds its own Fluxed Armor Plating and Flux-Infused Chestplate Assembly. I've renamed the Redstone Arsenal JAR so that Forge would hopefully pick it up first, and edited the config to no avail.

<img width="126" alt="screen shot 2018-04-10 at 2 33 55 am" src="https://user-images.githubusercontent.com/38228372/38542505-a50259e4-3c67-11e8-9ffc-378e35a37bb5.png">

I haven't been able to convince the mod to use the Redstone Arsenal Items. Am I missing something here?

I am using SimplyJetpacks 2.2.2.28, and Redstone Arsenal 2.3.11.5

**Comment by Tomson124** [comment]
Is Redstone Arsenal integration enabled in the configs of SJ2?

**Comment by 347Online** [comment]
Not only is Redstone Arsenal Integration enabled, but adding those items when RA is not present is also disabled.

**Comment by Tomson124** [comment]
I will have a look into it.

**Comment by 347Online** [comment]
Much appreciated, thank you.

**Comment by Tomson124** [comment]
Just pushed a fix for this, just look at the latest build on jenkins (link in the repo's readme).
Could you do me a favor? And test if everything works as it should when Redstone Arsenal is not installed but the "Add RA Items if not installed" config option is enabled?

**Comment by 347Online** [comment]
Looks like everything is on the up!
RA + SJ -> No Chestplate Assembly, Only one kind of Plating
SJ, no RA -> Recipe for plating is Signalum and Diamonds.

I didn't even know that recipe existed, because it was detecting the ingots and crystals just fine, building a recipe out of those.

Everything is good now! Thank you so much for your help!

I appreciate you. :)

Let me know if there's anything else I can do to assist you.

~Jake

**Comment by Tomson124** [comment]
No problem, thanks for the heads up didn't realized that this was not working right before.
Feel free join the discord (link in repo's readme), always glad to have people helping me test things.
