### ISSUE TITLE
Fluxpack crafting recipes are bugged

### ISSUE THREAD

**Issue by Xiaminou** [CyberdyneCC/SimplyJetpacks-2#69]
![2018-04-12_14 35 50](https://user-images.githubusercontent.com/8670392/38678183-9ca125fa-3e60-11e8-89a8-4d41eb623bd8.png)

As you can see you can use any tier of power cell to craft fluxpacks.

Minecraft: 1.12.2
Forge: 2641
Mods: [list.txt](https://github.com/Tomson124/SimplyJetpacks-2/files/1903151/list.txt)

**Comment by Tomson124** [comment]
Could you try this with only SJ2, Thermal mods and AE2 installed? As I can not reproduce this in my dev environment...
