### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Sermax18** [CyberdyneCC/SimplyJetpacks-2#7]
http://pastebin.com/6iiTW6Cp

**Comment by Tomson124** [comment]
Can you provide more information? How to reproduce? What did you do before it happened? Any config changes made?

**Comment by Sermax18** [comment]
it happened i install simply jetpacks 2.0.2.10.no

**Comment by Tomson124** [comment]
It is probably related to a change in the new forge veresion, I will have a look at it

**Comment by Tomson124** [comment]
It is probably related to a change in the new forge veresion, I will have a look at it
