### ISSUE TITLE
Flux-Infused Jetplate 50M/60M RF

### ISSUE THREAD

**Issue by Xiaminou** [CyberdyneCC/SimplyJetpacks-2#70]
![2018-04-12_14 47 17](https://user-images.githubusercontent.com/8670392/38678290-dee6622c-3e60-11e8-869c-dc01e1a03645.png)
Flux-Infused Jetplate shows a total capacity for 60M but stops at 50M.

Minecraft: 1.12.2
Forge: 2641
Mods: [list.txt](https://github.com/Tomson124/SimplyJetpacks-2/files/1903151/list.txt)

**Comment by Tomson124** [comment]
That's very odd as in my dev environment it shows 50M which is its default value. Did you change something in the config? And could you please test if this problem still persists if you just load the game with SJ2 and Thermal mods?

**Comment by Xiaminou** [comment]
You're right, I can't reproduce it with just a few mods, even tried with my resources pack but nope. I wonder what could be doing that.

**Comment by Xiaminou** [comment]
Oh nevermind, I know what this is, it's a simple config mismatch for some reason, maybe at some point it was 60M and got reduced to 50M later, apparently my client still had the 60M config and my server had the 50M.
I never touched SJ's config file which is why it didn't occur to me.

**Comment by Tomson124** [comment]
If you updated recently to SJ2 would be best to delete the config and let it generate a new one and then do your adjustments (if any needed)
