### ISSUE TITLE
Leadstone jetpack changes to Resonant or higher grade when shot at by Ghasts

### ISSUE THREAD

**Issue by GreatestFool** [CyberdyneCC/SimplyJetpacks-2#73]
Playing on my Forever Stranded Lost Souls server, just found a ghast temple and a shit ton of ghasts spawned. Wasn't really focusing that much on my inventory, but when things calmed down a bit I was launched ahead. I checked my inventory and [found a resonant jetpack in place of my leadstone one](https://imgur.com/a/TROVl). This has since happened later and also when shot at by the Wither.

**Comment by Tomson124** [comment]
Could you provide me a list of the mods, would be easier than digging the modpack name and the the mod list.
But it seems that you use "Levels" a mod which already had that strange behaviour with my mod in an previous version.

**Comment by GreatestFool** [comment]
Sorry for the late reply. When you say list, do you want the name of the mods as well as their mod version? If it isn't something I need exactly compile, [then this should do fine?](https://minecraft.curseforge.com/projects/forever-stranded-lost-souls/relations/dependencies). It is probably some of the levels mod that is causing this issue, if it has happened earlier then.

**Comment by GreatestFool** [comment]
[If you _did_ want a list of mods with their names and version included, I compiled it just in case.](https://pastebin.com/tbA39iCy)

**Comment by Tomson124** [comment]
Could you please try if the problem persists when you remove the Levels mod?

**Comment by GreatestFool** [comment]
I have tried it, and it does not seem like the issue persists when the Levels mod is disabled. It must be that then. That mod is also causing issues with Sync as well. Thanks for the help though, greatly appreciate it.

**Comment by Tomson124** [comment]
That's because the mod messes a lot with the NBT and Metadata of items, which are the two things my mod relies on when deciding wether it is a tier 2 or tier 3 jetpack. If I have time I will see if there is something on my end that I can change so it works better.

**Comment by GreatestFool** [comment]
Ah, that explains it. No worries though, I can just disable it. Again, thanks for the help.
