### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by Serifina** [CyberdyneCC/SimplyJetpacks-2#76]
Minecraft: 1.12.2
Forge: 2673
Simply Jetpacks: 2.2.3.33

Crashlog here: https://gist.github.com/Serifina/ea8ec8d668c7303ef5d076c1666e14ac

**Comment by GreatestFool** [comment]
You have an invalid recipe it seems.

**Comment by Tomson124** [comment]
Did you install or remove a mod after you installed SimplyJetpacks2?

**Comment by Serifina** [comment]
I had added two mods (Platforms and ShetiPlainsCore) but I disabled the, and the error still recurred. I also removed all my SJ2 craft tweaker recipes (which was just removing some to disable the jetplate). Still recurred. As a precaution, I also redownloaded the mod. Same crash.

**Comment by Tomson124** [comment]
Could you please try setting the RA integration in the config to false and the "Add Redstone Arsenal items if not installed" to true?

**Comment by Serifina** [comment]
When I went to change it, I realized RA's integration was already set to false, as was the Add RA items if not installed option. I think I'd disabled it because I was trying to disable the jetplate. Enabling the Add RA items solved the crash, as did enabling RA integration, either way.

**Comment by Tomson124** [comment]
Okay, then I am sure what it is. Should probably add somekind of failsafe so this doesn't happen when the configs are set in a specific way.

**Comment by Serifina** [comment]
Thanks for the assistance. Sorry for breaking it. :)
