### ISSUE TITLE
Illegal Argument Exception, equal objects must have equal hashcodes

### ISSUE THREAD

**Issue by GreatestFool** [CyberdyneCC/SimplyJetpacks-2#77]
Don't know why, or if it is some other mod interfering with this mod, but right now on the newest version of thermal expansion and this I am experiencing a crash. Thought I should mention it here. [Here's the crash log](https://pastebin.com/9H0fMt1j). [And here's the mod list if you need it](https://pastebin.com/TVjdsh1Y).

**Comment by Keridos** [comment]
Nothing in that logs mentions SimplyJetpacks anywhere.
I see cofhcore and tinkers construct in there.

**Comment by GreatestFool** [comment]
Well yea, but it is causing interference with something in thermal expansion. Whether that is thermal expansion causing the problem or not I don't know, but disabling Simply Jetpacks fixes the problem so I thought I should mention it.

Do you think this is something cofh has to fix on their side?

**Comment by Tomson124** [comment]
What you could try is reproducing the error with just SimplyJetpacks2, cofh mods and Tinkers and see if it happens then, too.

**Comment by GreatestFool** [comment]
Seems like the problem has been fixed in the newer releases of cofh. So I guess it was on their side.
