### ISSUE TITLE
Armor Plating can no longer be upgraded

### ISSUE THREAD

**Issue by SHEERSPECTOR** [CyberdyneCC/SimplyJetpacks-2#78]
After most recent update to CoFH and Simply Jetpacks, recipes for higher tiers of armor plating no longer appear in JEI.  Induction smelter no longer accepts any armor plating as valid inputs.

**Comment by Keridos** [comment]
Yes, can confirm this.

**Comment by bochen415** [comment]
This makes crafting the Flux-Infused JetPlate impossible since the armored jetpack is used in the recipe.

**Comment by Tomson124** [comment]
This is already fixed on my dev-environment, but as the new Win10 1803 update completely killed my boot drive somehow, you have to wait till tomorrow evening (German time), then I am back at home and can do it on my main PC instead of the notebook.

**Comment by TheLimePixel** [comment]
I think you're a bit late... :P
