### ISSUE TITLE
Jetpacks charge values are incorrect

### ISSUE THREAD

**Issue by SplitInfinitive** [CyberdyneCC/SimplyJetpacks-2#83]
Jetpacks work perfectly, but some hold less power then they say is their actual max and some hold more.

See screenshot for example: 

![2018-05-09_12 20 18](https://user-images.githubusercontent.com/24683195/39846072-ee7437c6-53b6-11e8-9e5d-3d582649cc14.png)

SimplyJetpacks2-2.2.4.34
Forge Version 2655

**Comment by Tomson124** [comment]
Did you try deleting the config and let it generate a new one?

**Comment by SplitInfinitive** [comment]
I can ask the server guys to re-generate one but AFAIK it's a default generated config.

**Comment by thundr** [comment]
This should be fixed with the recent changes to config, please reopen if not.
