### ISSUE TITLE
[1.12.2] Warning when loading into world with the Mod "VanillaFix"

### ISSUE THREAD

**Issue by Gbergz** [CyberdyneCC/SimplyJetpacks-2#85]
Hey! When i load into the world with the Mod VanillaFix and using Simply Jetpacks 2 Mod i get this Crash/Warning 

[HASTEBIN LINK](https://paste.dimdev.org/penatifici.txt)

Any ideas on how to fix it?

**Comment by Bneboy** [comment]
I get a similar crash. I tested it with the latest development build (also latest stable build) of SJ2, (build 36) and I get the same/similar crash on the latest released build on CurseForge.

Here's the crash report from me using the latest build 36, if it helps the dev/devs at all.

https://pastebin.com/UtMBNKgd

**Comment by Tomson124** [comment]
This is the same thing discussed in #82 
There is a config option in VanillaFix now, which you have to enbable, then it wont crash the game anymore.
But I know this is a problem on my side and I will fix this.

**Comment by NicosaurusRex99** [comment]
https://paste.dimdev.org/ehefevahow.txt

**Comment by thundr** [comment]
This should be fixed with the recent changes to config, please reopen if not.
