### ISSUE TITLE
[Suggestion] Add support for Redstone repositery

### ISSUE THREAD

**Issue by Skillotic0703** [CyberdyneCC/SimplyJetpacks-2#86]
Redstone repositery is the port of redstone armory in 1.12. It would be cool if there was a jetplate that had a texture that corresponds to the one of the Enderium Flux Armor.

**Comment by thundr** [comment]
I am working with Tomson on doing just that :)

**Comment by Skillotic0703** [comment]
Thank you!

**Comment by thundr** [comment]
Will be added in #93
