### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by Zarthong** [CyberdyneCC/SimplyJetpacks-2#87]
CRASH: https://pastebin.com/jYpXe4s0

**Comment by Tomson124** [comment]
You cannot just say game crashed and post the crashlog....
I need information! First of all always put crashlog on pastebin and post link here. Secondly please show me your SJ2 configs.

**Comment by Zarthong** [comment]
Crash: https://pastebin.com/6mtknKHc
Config: https://pastebin.com/ZBnGWu5m (Also tried with EnderIO Jetpacks set to true)
Client Config: https://pastebin.com/AiZBGA2t

New version still crashes

**Comment by Tomson124** [comment]
Try turning off the vanilla integration as this feature is currently not really working correctly and will be redone in the future.
