### ISSUE TITLE
Fluxpacks

### ISSUE THREAD

**Issue by Sermax18** [CyberdyneCC/SimplyJetpacks-2#9]
where fluxpacks?

**Comment by Tomson124** [comment]
So first of all... Please take the time to form a full sentence so I can understand what you asking.
Next: This is a mod that is still **work in progress**!!
The version I release are more or less by-products of my development. This means the mod can be highly unstable and it will be lacking features as I'm "updating" them one after the other.
I already said that a few times (and wrote it on github, curseforge, reddit).
If you are not familiar with java or minecraft coding then I tell you something: **Programming takes time!** A lot of time.
I am working full time and do minecraft modding in my freetime but some of that freetime is also used for my personal/private life...
So once and for all: This mod is a WIP and Fluxpacks and any other feature will be ready when it is ready!
If you want to know how well I'm making progress just check on my twitter from time to time: [https://twitter.com/Tomson124](https://twitter.com/Tomson124)

**Comment by Tomson124** [comment]
"Fixed" with 3dc620a0608cf76e809ca749b491831b2c500d3c
