### ISSUE TITLE
Change top-left text renderer to use RenderGameOverlayEvent.Text

### ISSUE THREAD

**Issue by LatvianModder** [CyberdyneCC/SimplyJetpacks-2#97]
That way it won't intersect with other mods using that event (like FTBUtilities). Should be a simple change.
![image](https://ss.latmod.com/pc/2018-06-10_23.40.59.png)

**Comment by thundr** [comment]
This looks like a straightfoward change. I'll get to it with the next round of patches.

**Comment by LatvianModder** [comment]
Only visual difference is that it has faint white/gray background
