### ISSUE TITLE
[Suggestion] Jetpacks require fuel and power

### ISSUE THREAD

**Issue by Xiaminou** [CyberdyneCC/SimplyJetpacks-2#99]
Would it be possible to have a config option so that jetpacks require fuel and power?
There are quite a few fluids in modded minecraft that would fit as fuel. Thermal Expansion's Refined Fuel and Grassoline, EnderIO's Rocket Fuel, Immersive Engineering's Biodiesel, Immersive Petroleum's Gasoline and more...
You could just base it off the Compression Dynamo's fuel value if Thermal Expansion is present.

I think most people would want that disabled by default. But others like myself may want to have both fuel and power required.

**Comment by thundr** [comment]
Tomson and I have talked a number of times about an SJ charging block or system, but until we settle on some concrete thoughts, I think we will close this for now.
